dist: bionic
language: ruby
jobs:
  include:
    - name: "Postgres 12"
      rvm: 2.7
      addons:
        apt:
          packages:
            - postgresql-12
      before_install:
        - sudo sed -i 's/port = 5433/port = 5432/' /etc/postgresql/12/main/postgresql.conf
        - sudo cp /etc/postgresql/{9.3,12}/main/pg_hba.conf
        - sudo pg_ctlcluster 12 main restart
        - createdb pgslice_test
      env:
        - PGUSER=postgres
script: bundle exec rake test
before_install:
  - createdb pgslice_test
notifications:
  email:
    on_success: never
    on_failure: change
