dist: bionic
language: ruby
jobs:
  include:
    - name: "Postgres 13"
      rvm: 2.7
      dist: focal
      addons:
        postgresql: "13"
        apt:
          sources:
            - sourceline: deb http://apt.postgresql.org/pub/repos/apt/ focal-pgdg main 13
              key_url: https://www.postgresql.org/media/keys/ACCC4CF8.asc
          packages:
            - postgresql-13
    - name: "Postgres 12"
      rvm: 2.7
      dist: focal
      addons:
        postgresql: "12"
        apt:
          packages:
            - postgresql-12
    - name: "Postgres 11"
      rvm: 2.6
      addons:
        postgresql: "11"
    - name: "Postgres 10"
      rvm: 2.5
      addons:
        postgresql: "10"
    - name: "Postgres 9.6"
      rvm: 2.4
      addons:
        postgresql: "9.6"
services:
  - postgresql
script: bundle exec rake test
before_install:
  - createdb pgslice_test
notifications:
  email:
    on_success: never
    on_failure: change
